### DISCUSSION TITLE
useHydrateAtoms atomsValues type

### DISCUSSION THREAD

**Discussion by ralexhassle** [pmndrs/jotai#2647] [Q&A] [answered]
Hi, 

Issue with TypeScript types when initializing atom families in Jotai:

I'm having trouble with TypeScript types when initializing atom families using Jotai. Everything seems to work, but TypeScript is not happy with the types passed to AtomsHydrator.

Here's the relevant code:

```ts
interface AtomsHydratorProps {
  atomValues: Iterable<
    readonly [WritableAtom<unknown, [any], unknown>, unknown]
  >;
  children: ReactNode;
}
function AtomsHydrator({ atomValues, children }: AtomsHydratorProps) {
  useHydrateAtoms(new Map(atomValues));
  return children;
}

interface ListBoxProps {
  items: Option[];
  defaultValues?: Option["value"][];
}
export const ComboBox = (props: ListBoxProps) => {
  const { items, defaultValues = [] } = props;

  const defaultAtomValues = items.map((item) => [
    itemAtomFamily(item),
    {
      value: item.value,
      label: item.label,
      checked: defaultValues.includes(item.value)
    }
  ]);

  return (
    <Provider>
      <AtomsHydrator atomValues={[[itemsAtom, items], ...defaultAtomValues]}>
        <Container>
          <Popover strategy="absolute">
            <SearchInput items={items} />
            <Overlay>
              <SearchResult />
              <Footer>{`${items.length} results`}</Footer>
            </Overlay>
          </Popover>
          <SelectedItems />
        </Container>
      </AtomsHydrator>
    </Provider>
  );
};
```

The problem seems to be with the type passed to AtomsHydrator. Specifically, I'm trying to initialize atom families, and TypeScript is not accepting the types. The error message I'm getting is:

```css
Type '([PrimitiveAtom<Option[]> & WithInitialValue<Option[]>, Option[]] | ((PrimitiveAtom<{ value: string | number; checked: boolean; label: string | undefined; }> & WithInitialValue<...>) | { ...; })[])[]' is not assignable to type 'Iterable<[WritableAtom<any, any, any>, any]>'.
  The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
    Type 'IteratorResult<[PrimitiveAtom<Option[]> & WithInitialValue<Option[]>, Option[]] | ((PrimitiveAtom<{ value: string | number; checked: boolean; label: string | undefined; }> & WithInitialValue<...>) | { ...; })[], any>' is not assignable to type 'IteratorResult<[WritableAtom<any, any, any>, any], any>'.
      Type 'IteratorYieldResult<[PrimitiveAtom<Option[]> & WithInitialValue<Option[]>, Option[]] | ((PrimitiveAtom<{ value: string | number; checked: boolean; label: string | undefined; }> & WithInitialValue<...>) | { ...; })[]>' is not assignable to type 'IteratorResult<[WritableAtom<any, any, any>, any], any>'.
        Type 'IteratorYieldResult<[PrimitiveAtom<Option[]> & WithInitialValue<Option[]>, Option[]] | ((PrimitiveAtom<{ value: string | number; checked: boolean; label: string | undefined; }> & WithInitialValue<...>) | { ...; })[]>' is not assignable to type 'IteratorYieldResult<[WritableAtom<any, any, any>, any]>'.
          Type '[PrimitiveAtom<Option[]> & WithInitialValue<Option[]>, Option[]] | ((PrimitiveAtom<{ value: string | number; checked: boolean; label: string | undefined; }> & WithInitialValue<...>) | { ...; })[]' is not assignable to type '[WritableAtom<any, any, any>, any]'.
            Type '((PrimitiveAtom<{ value: string | number; checked: boolean; label: string | undefined; }> & WithInitialValue<{ value: string | number; checked: boolean; label: string | undefined; }>) | { ...; })[]' is not assignable to type '[WritableAtom<any, any, any>, any]'.
              Target requires 2 element(s) but source may have fewer.ts(2322)
```

How can I properly type AtomsHydrator to accept the atom families initialization?

Thank you in advance for your help!
